apiVersion: 1

datasources:
  - name: Prometheus (local)
    uid: prometheus-local
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: 2s
